name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
    types: [opened, synchronize]

env:
  SKIP_DEPLOYMENT: ${{ contains(join(github.event.commits.*.message), '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: npm install 
        run: npm install
        
      - name: lint
        run: npm run eslint

      - name: build
        run: npm run build
      
      - name: Discord failure notification
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: error
          color: '#ff00aa'
          description: commit ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }} by ${{ github.actor }} broke the build
          text: Build failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: test
        run: npm test

      - name: e2e tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run start-prod
          wait-on: http://localhost:5000

      - name: Setup Flyctl
        if: ${{ github.event_name == 'push' && env.SKIP_DEPLOYMENT == 'false' }}
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy app
        if: ${{ github.event_name == 'push' && env.SKIP_DEPLOYMENT == 'false' }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Discord success notification
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          color: '#ff00aa'
          description: to ${{ secrets.DEPLOYED_APP_URL}} by ${{ github.actor }}
          text: A new version of Pokedex deployed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    needs: [simple_deployment_pipeline]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          DEFAULT_BUMP: patch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
